import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-geist-mono"
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",

});

export const metadata = {
  title: {
    default: "Create Next App",
    template: "%s - User",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        // className={`${geistSans.variable} bg-white`} //we can add multiple fonts like this
        className={`${montserrat.variable} ${geistMono.variable} ${geistSans.className} bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
